# Generated by Django 3.1.4 on 2022-07-08 07:30

import django.core.validators
from django.db import migrations, models
import tinymce.models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220708_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sejarah',
            name='Judul',
        ),
        migrations.RemoveField(
            model_name='sejarah',
            name='gambar',
        ),
        migrations.AddField(
            model_name='sejarah',
            name='isi',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=models.FileField(blank=True, null=True, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size]),
        ),
    ]
