# Generated by Django 3.1.4 on 2022-07-08 16:46

import django.core.validators
from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220708_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurikulum',
            name='sks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='foto',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dosen',
            name='s3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persyaratan',
            name='file_pdf',
            field=models.FileField(upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=models.FileField(upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size]),
        ),
        migrations.AlterField(
            model_name='sop',
            name='file_pdf',
            field=models.FileField(upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size]),
        ),
    ]
