# Generated by Django 3.1.4 on 2022-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220709_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akreditasi',
            options={'verbose_name_plural': 'Akreditasi'},
        ),
        migrations.RemoveField(
            model_name='akreditasi',
            name='tingkat',
        ),
        migrations.AddField(
            model_name='akreditasi',
            name='jenis',
            field=models.PositiveIntegerField(choices=[(1, 'akreditasi S1'), (2, 'akreditasi S2'), (3, 'akreditasi S3'), (4, 'SK AKREDITASI')], default=1),
        ),
    ]
