# Generated by Django 3.1.4 on 2022-07-09 08:41

import django.core.validators
from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220709_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akreditasi',
            name='gambar',
        ),
        migrations.AddField(
            model_name='akreditasi',
            name='upload_file',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf']), website.models.file_size]),
            preserve_default=False,
        ),
    ]
