# Generated by Django 3.1.4 on 2022-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220709_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='akreditasi',
            name='Judul',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
