# Generated by Django 3.1.4 on 2022-07-09 15:04

import django.core.validators
from django.db import migrations, models
import tinymce.models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_akreditasi_judul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', tinymce.models.HTMLField()),
                ('gambar', models.FileField(blank=True, null=True, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf']), website.models.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Beasiswa',
            },
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tgl_kegiatan', models.DateField(verbose_name='tanggal kegiatan')),
                ('tgk_kegiatan', models.TimeField(verbose_name='waktu kegiatan')),
                ('keterangan', tinymce.models.HTMLField()),
                ('gambar', models.FileField(blank=True, null=True, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kegiatan',
            },
        ),
        migrations.DeleteModel(
            name='Informasi',
        ),
    ]
