# Generated by Django 3.1.4 on 2022-07-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_lembaga_mhs_prestasi_mhs_statistik_mhs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kegiatan',
            old_name='tgk_kegiatan',
            new_name='waktu_kegiatan',
        ),
        migrations.AddField(
            model_name='statistik_mhs',
            name='lulus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
