# Generated by Django 3.1.4 on 2022-07-11 18:52

import django.core.validators
from django.db import migrations, models
import tinymce.models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220712_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beasiswa',
            name='gambar',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='gambar',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='keterangan',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
