# Generated by Django 3.1.4 on 2022-07-11 20:12

import django.core.validators
from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20220712_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalender_akademik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kalender Akademik',
            },
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fasilitas',
            name='gambar',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='file_pdf',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['[pdf]']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengabdian',
            name='file_pdf',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadmap_penelitian',
            name='file_pdf',
            field=models.FileField(default=1, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), website.models.file_size]),
            preserve_default=False,
        ),
    ]
