# Generated by Django 3.1.4 on 2022-07-12 06:18

import django.core.validators
from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220712_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal_kuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), website.models.file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Kalender Akademik',
            },
        ),
        migrations.AlterModelOptions(
            name='lembaga_mhs',
            options={'verbose_name_plural': 'Lembaga Mahasiswa'},
        ),
        migrations.AlterModelOptions(
            name='prestasi_mhs',
            options={'verbose_name_plural': 'Prestasi Mahasiswa'},
        ),
    ]
