# Generated by Django 3.1.4 on 2022-07-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20220712_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='judul',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='sumber',
            field=models.CharField(max_length=200),
        ),
    ]
