# Generated by Django 3.1.4 on 2022-07-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20220713_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendik',
            name='Tanggal_Lahir',
            field=models.DateField(),
        ),
    ]
